prisms-center/phaseField

applications/allenCahn/main.cc, applications/betaPrimePrecipitateEvolution/main.cc, applications/cahnHilliard/main.cc, applications/coupledCahnHilliardAllenCahn/main.cc, applications/coupledCahnHilliardMechanics/main.cc, applications/fickianDiffusion/main.cc, applications/mechanics/main.cc
I changed the namespace for the MPI calls.
=> Fixed name space

applications/allenCahn/main.cc, applications/betaPrimePrecipitateEvolution/main.cc, applications/cahnHilliard/main.cc, applications/coupledCahnHilliardAllenCahn/main.cc, applications/coupledCahnHilliardMechanics/main.cc, applications/fickianDiffusion/main.cc, applications/mechanics/main.cc, src/matrixfree/solve.cc
Changed the iteration loop so that it does totalIncrements steps rather than totalIncrements-1
=> Output final result

src/matrixfree/outputResults.cc
I made the same changes that were made in the fa67a0e075dfe9a567306c416075bf42633706d1 commit last April
=> reapplied earlier fix so that outputs > 1,000,000 are formatted properly

applications/CHAC_anisotropy/ICs_and_BCs.h, applications/CHAC_anisotropyRegularized/ICs_and_BCs.h
Hi, @stvdwtt , I have made the change which was mentioned in the issue [40](https://github.com/prisms-center/phaseField/issues/40). 
Please check and merge it.
=> delete 4 extra lines in ICs_and_BCs.h for CHAC application

include/fields.h, include/matrixFreePDE.h, src/matrixfree/init.cc, src/matrixfree/solveIncrement.cc
Moved the various fields flags about boundary conditions to the field class & refactored the application of BCs in solveIncrement.cc
=> Refactoring application of BCs in solveIncrement

applications/grainGrowth/equations.cc, applications/grainGrowth/postprocess.cc
Added [[maybe_unused]] in postprocess.cc and equations.cc to suppress warnings
=> Added `[[maybe_unused]]` to prevent warnings in grainGrowth application

applications/allenCahn_conserved/customPDE.h
There was a refactor of the explicit update and renaming of the scalar and vector inverted matrices a while back. This was not applied to any applications that override `solveIncrement()` like the conserved Allen-Cahn application.
This PR fixes that.
=> Fixed incomplete refactoring of methods in customPDE override

applications/grainGrowth/ICs_and_BCs.cc
There was a variable with the same name as the function variable in grain growth's `ICs_and_BCs.cc`. 
Closes #255
=> Rename point variable in grain growth application

.gitignore
Add *.vscode\* and *.zip and *.tar.gz to gitignore
=> Add vscode and zip to gitignore

postprocess_scripts/vtutopython.py
Script to load vtu files into python. Creates a file containing a dictionary of requested fields, which can easily be loaded in python, or the core function can be copied and used directly.
=> Added script to load vtu into python

contrib/utilities/update_application.sh
Usage:
./contrib/utilities/update_application.sh SRC_DIR /applications/APP_DIR
with:
SRC_DIR pointing toward the PRISMS-PF source directory
APP_DIR pointing toward the application directory to update
=> Script to update applications to newest version

doc/doxygen/user_manual/installation/install_prereqs.md
=> Updated dead deal.II download link

.github/workflows/linux.yml, include/core/fields.h, tests/CMakeLists.txt, tests/core/fields.cc
Redid `fields.h` with some more defensive programming. Also added a unit test and updated the CI to run the unit tests.
=> Field unit tests

.github/workflows/clang-format.yml, .github/workflows/clang-tidy.yml, .github/workflows/github-pages.yml, .github/workflows/linux.yml
Added some restrictions on when to run certain workflows.
Closes #368 
=> Restrict CI runs

applications/allenCahn_conserved/customPDE.h, include/core/matrixFreePDE.h, src/core/invM.cc, src/core/solvers/solveIncrement.cc
Adding warning for max nonlinear iterations and more descriptive print statements.
Closes #302, #127 
=> Updating nonlinear printing info

include/grains/FloodFiller.h, include/grains/SimplifiedGrainRepresentation.h, src/core/initial_conditions/initialConditions.cc, src/grains/FloodFiller.cc, src/grains/SimplifiedGrainRepresentation.cc, src/grains/reassignGrains.cc
The GrainSet class holds information about grain index, order parameter index, and vertex list for a _single grain_ so calling it a GrainSet is confusing.
=> Rename GrainSet class to Grain

include/prismspf/core/pde_problem.h, include/prismspf/utilities/compute_integral.h, include/prismspf/utilities/element_volume.h
Works for both scalar and vector fields.
Didn't bother to add the front-end stuff for the user to toggle.
=> Adding compute integral function

.gitignore
=> Cleaned up gitignore

include/prismspf/user_inputs/output_parameters.h, src/core/solution_output.cc, src/user_inputs/input_file_reader.cc, src/user_inputs/user_input_parameters.cc
Closes #506 and #131 
@zachcroft This should help.
=> Adding output types and output subdivisions

include/prismspf/core/constraint_handler.h, include/prismspf/user_inputs/boundary_parameters.h, src/core/constraint_handler.cc, src/core/matrix_free_operator.cc, src/core/pde_problem.cc, src/core/triangulation_handler.cc, src/solvers/linear_solver_gmg.cc, src/user_inputs/user_input_parameters.cc, tests/automatic_tests/allen_cahn_explicit/ICs_and_BCs.cc, tests/automatic_tests/allen_cahn_explicit/custom_pde.h, tests/automatic_tests/allen_cahn_implicit/ICs_and_BCs.cc, tests/automatic_tests/allen_cahn_implicit/custom_pde.h, tests/automatic_tests/blank/ICs_and_BCs.cc, tests/automatic_tests/blank/custom_pde.h, tests/automatic_tests/cahn_hilliard_explicit/ICs_and_BCs.cc, tests/automatic_tests/cahn_hilliard_explicit/custom_pde.h, tests/automatic_tests/fracture/CMakeLists.txt, tests/automatic_tests/fracture/ICs_and_BCs.cc, tests/automatic_tests/fracture/custom_pde.h, tests/automatic_tests/fracture/equations.cc, tests/automatic_tests/fracture/gold_output.txt, tests/automatic_tests/fracture/parameters.prm, tests/automatic_tests/heat_equation_steady_state/ICs_and_BCs.cc, tests/automatic_tests/heat_equation_steady_state/custom_pde.h, tests/automatic_tests/mechanics/ICs_and_BCs.cc, tests/automatic_tests/mechanics/custom_pde.h, tests/automatic_tests/precipitate_explicit/ICs_and_BCs.cc, tests/automatic_tests/precipitate_explicit/custom_pde.h, tests/automatic_tests/precipitate_explicit/equations.cc, tests/automatic_tests/run_automatic_tests.py
Still some things to do before this is ready.
@wband Does the application look alright visually? I ask this because the dndt term gets calculated before the strain field (u) is initially solved. I'm not sure how much an issue this lag causes.
=> Fracture app & fixes

.github/workflows/clang-tidy.yml, .github/workflows/compile_applications.yml, contrib/utilities/clang_tidy.sh
The 18 version doesn't work well for the docker image and gives false positives.
=> Updating run-clang-tidy to 20

README.md
=> Some typos and dead link in README.md

CMakeLists.txt, include/prismspf/core/parse_cmd_options.h
=> zlib dependency & caliper defaults

src/core/nonuniform_dirichlet.cc, src/core/pde_problem.cc, src/core/solution_output.cc, src/solvers/nonexplicit_co_nonlinear_solver.cc, tests/automatic_tests/allen_cahn_implicit/gold_output.txt, tests/automatic_tests/allen_cahn_implicit/parameters.prm, tests/automatic_tests/fracture/custom_pde.h, tests/automatic_tests/fracture/gold_output.txt, tests/automatic_tests/fracture/parameters.prm, tests/automatic_tests/run_automatic_tests.py
=> Fixes for ghost zone application and time-dependendent dirichlet boundary conditions

include/prismspf/user_inputs/checkpoint_parameters.h, include/prismspf/user_inputs/output_parameters.h, include/prismspf/user_inputs/temporal_discretization.h, src/core/pde_problem.cc
=> Print info for first timestep & no additional increment for time-independent problems

include/prismspf/user_inputs/boundary_parameters.h, tests/automatic_tests/fracture/parameters.prm, tests/automatic_tests/heat_equation_steady_state/parameters.prm
=> Constant fields don't need boundary conditions

CMakeLists.txt, cmake/macros/macro_prisms_pf_autopilot.cmake, cmake/setup_application.cmake, include/prismspf/core/pde_problem.h, include/prismspf/core/timer.h, include/prismspf/solvers/explicit_constant_solver.h, include/prismspf/solvers/explicit_postprocess_solver.h, include/prismspf/solvers/explicit_solver.h, include/prismspf/solvers/linear_solver_gmg.h, include/prismspf/solvers/linear_solver_identity.h, include/prismspf/solvers/nonexplicit_auxiliary_solver.h, include/prismspf/solvers/nonexplicit_co_nonlinear_solver.h, include/prismspf/solvers/nonexplicit_linear_solver.h, include/prismspf/solvers/nonexplicit_self_nonlinear_solver.h, src/core/pde_problem.cc, src/core/timer.cc, src/solvers/explicit_postprocess_solver.cc, src/solvers/explicit_solver.cc, src/solvers/nonexplicit_auxiliary_solver.cc, src/solvers/nonexplicit_co_nonlinear_solver.cc, src/solvers/nonexplicit_linear_solver.cc, src/solvers/nonexplicit_self_nonlinear_solver.cc
=> Updating timer class

include/prismspf/user_inputs/linear_solve_parameters.h, include/prismspf/user_inputs/nonlinear_solve_parameters.h, include/prismspf/user_inputs/user_input_parameters.h, tests/unit_tests/CMakeLists.txt, tests/unit_tests/user_inputs/nonlinear_solve_parameters.cc
=> Added nonlinear solve parameter unit tests

include/prismspf/core/variable_attribute_loader.h
=> variable_attribute_loader functions should be public
