applications/cahnHilliard/.project, src/models/mechanics/anisotropy.h
I believe there is a bug in how the Cij tensor is formed for 2D anisotropic calculations (in anisotropy.h). In previous versions of the code (e.g. Nov 26, 2014), all of the elements of Cij are nonzero. In the current code, the (1,0), (2,0), and (2,1) elements aren't assigned.
=> 2 d cij bug

src/matrixfree/init.cc, src/matrixfree/solveIncrement.cc, tests/automatic_tests/test_results.txt
1) Expanded the criteria to consider that the system has Dirichlet boundary conditions (BC) to when they are nonuniform. Previously, if only nonuniform Dirichlet conditions were set for a field. The code did not recognize them as Dirichlet BC and missed setting them.
2) Fixed an incomplete loop to detect Dirichlet BC in /src/matrixfree/init.cc. Previously the loop was over field variables. Currently it is over boundaries.
3) Fixed bug that caused time-dependent Dirichlet boundary conditions to be updated except when mesh refinement was applied.
=> Fixed issues with nonuniform Dirichlet boundary conditions

src/matrixfree/solveIncrement.cc
1. Auxiliary terms have dirichlet boundaries applied every increment regardless of input boundary conditions
2. NaN solutions are checked every increment  
Fixing these to more closely resemble the process for explicit terms decreases computation time greatly. These changes have been tested on the Cahn-Hilliard app to produce identical results with an ~25% decrease in computation time.
=> Increased auxiliary term performance

include/userInputParameters.h, src/inputFileReader/inputFileReader.cc, src/matrixfree/nucleation.cc, src/userInputParameters/userInputParameters.cc
For the nucleation section of parameters.prm, options were added to:
- Enable evolution of field variables before the first nucleus appears
- Set a nucleation start time
- Set a nucleation end time
=> Added input parameter options for nucleation

src/matrixfree/computeLHS.cc, src/matrixfree/solveIncrement.cc
1. Constrained DoF in the residual set can be set to zero with `set_zero`
2. Dirichlet constraints can be distributed with `distribute`
=> Minor simplifications for dirichlet BCs in implicit solves

include/matrixFreePDE.h, src/matrixfree/initForTests.cc, src/matrixfree/initialConditions.cc, src/matrixfree/invM.cc, src/matrixfree/outputResults.cc, src/matrixfree/solveIncrement.cc, tests/unit_tests/test_invM.h, tests/unit_tests/test_setRigidBodyModeConstraints.h
The inverted diagonal mass matrices (invM) for scalar and vector fields are different, so they must both be considered when updating the explicit solution. Previously, the type of the first occurring explicit field was used to calculate the invM. This led to issues if scalar & vector explicit fields were included (as only 1 field could be updated correctly).
Now, the scalar & vector invMs are calculated if there are scalar, vector, or scalar & vector fields whenever `computeInvM()` is called. 
I've also added a unit test for the invM of vector fields.
=> invM for scalar & vector fields

applications/CHiMaD_benchmark6b/customPDE.h, applications/_nucleating_precipitates_MgRE/equations.h, applications/allenCahn_conserved/customPDE.h, applications/nucleationModel/equations.cc, applications/nucleationModel_preferential/equations.cc, src/OrderParameterRemapper/OrderParameterRemapper.cc, src/matrixfree/boundaryConditions.cc, src/matrixfree/computeIntegral.cc, src/matrixfree/init.cc, src/matrixfree/initForTests.cc, src/matrixfree/markBoundaries.cc, src/matrixfree/nucleation.cc, src/matrixfree/reinit.cc, src/matrixfree/setNonlinearEqInitialGuess.cc, src/matrixfree/solveIncrement.cc, src/matrixfree/utilities.cc, src/parallelNucleationList/parallelNucleationList.cc
Range based loops from C++11 are a bit more readable and a good way to simplify the loop structures. 
I converted all the loops (except for those `FloodFiller.cc`).
=> Switching to range based loops

applications/precipitateEvolution/equations.cc
Edited the equation.cc code during the Github Tutorial. I hope it is fine!
Thanks.
=> Added `[[maybe_unused]]` variables for this application: precipitateEvolution

applications/allenCahn/equations.cc, applications/allenCahn/postprocess.cc
qualifier to suppress warnings in allenCahn app
=> Added `[[maybe_unused]]` for the allenCahn applications

include/model_variables.h, include/variableContainer.h, src/matrixfree/computeLHS.cc, src/userInputParameters/loadVariableAttributes.cc, src/variableContainer/variableContainer.cc
The change variables were hard coded so that only the first `TIME_INDEPENDENT` equation would have its change variable (for Newton-Picard iteration). This prevented the addition of multiple `TIME_INDEPENDENT` (#166) equations. To fix this, I switched the `FEEvaluation` vectors to unordered maps instead.
This way, we can assign the `FEEvaluation` to the global variable index rather than the index of variable type (e.g. phi might be the 4th explicit variable and the 5th global variable. In the prior scheme we would index based on the 4th explicit). Doing so also reduced the convolutedness of `loadVariableAttributes.cc` and `variableContainer.cc`. 
Some minor optimizations were also made in regard to dereferencing over and over. Before we had this
``` …
```
=> Fix multiple linear/nonlinear solves

src/userInputParameters/setTimeStepList.cc
- Refactored parts `setTimeStepList.cc` to make it more readable. 
- If the number of outputs is set to 0, there are no outputs, regardless of the output type. Previously this was ignored for lists; however, the user should ignore the parameter and let PRISMS-PF use the default value of 10. 
- Added assertions for `N_PER_DECADE` so that the total increments is greater than 1. 
- The log spacing is working as intended. Note that our log spacing does not correspond to something like MATLAB's logspace because they begin at 10^0 while we start at 0. 
Closes #157
=> Fixed log spacing

include/userInputParameters.h
Added assertions for when we try to access an invalid map entry in `model_constants`.
Say we have:
```
double MnV = userInputs.get_model_constant_double("not_a_variable");
```
This will throw this error when compiled in debug mode:
```
The violated condition was: 
model_constant_name_map.find(constant_name) != model_constant_name_map.end()
Additional information: 
PRISMS-PF Error: Mismatch between constants in parameters.prm and
customPDE.h. The constant that you attempted to access was not_a_variable.
```
Closes #102
=> Adding assertions for model constants

.github/workflows/linux.yml
There is now a 60 minute time limit in the `run_automatic_tests.py` step and a total time limit of 120 minutes. This works for now, but could be narrowed down in the future. 
Closes #266
=> Adding linux CI timeout

src/matrixfree/initialConditions.cc
=> read the name given in parameters.prm instead of the internal variable name

src/variableAttributes/variableAttributes.cc
fixes #337 
Determine whether other_variable is nonlinear (1): LHS has any nonexplicit dependency.
Added some comments.
=> fixed nonlinearity criterion

CMakeLists.txt, include/config.h.in
Adding an optional dependency for caliper to profile portions of code. This is primarily oriented to developers, but could be useful for users in optimizing their application code.
=> adding optional caliper dependency

include/core/matrixFreePDE.h, include/core/refinement/AdaptiveRefinement.h, include/core/typeDefs.h, include/core/variableContainer.h, include/grains/FloodFiller.h, include/grains/OrderParameterRemapper.h, include/utilities/utilities.h, src/core/checkpoint.cc, src/core/init.cc, src/core/initial_conditions/initialConditions.cc, src/core/outputResults.cc, src/core/postprocessing/computeIntegral.cc, src/core/postprocessing/postprocessor.cc, src/core/refinement/AdaptiveRefinement.cc, src/core/reinit.cc, src/core/solvers/computeLHS.cc, src/core/solvers/computeRHS.cc, src/core/solvers/setNonlinearEqInitialGuess.cc, src/core/solvers/solveIncrement.cc, src/core/variableContainer.cc, src/grains/FloodFiller.cc, src/grains/OrderParameterRemapper.cc
Removed some of the datatypes and add function that converts a std::vector into a 1st rank dealii::Tensor of vectorized arrays.
Closes #274
=> Helper function for converting `std::vector` into `Tensor<VectorizedArray> `

applications/CHiMaD_benchmarks/CHiMaD_benchmark1c/customPDE.h, applications/CHiMaD_benchmarks/CHiMaD_benchmark6b/customPDE.h, applications/allenCahn_conserved/customPDE.h, include/core/boundary_conditions/nonUniformDirichletBC.h, include/core/exceptions.h, include/core/initial_conditions/initialConditions.h, include/core/matrixFreePDE.h, include/core/userInputParameters.h, include/core/variableContainer.h, include/core/variableValueContainer.h, include/field_input/IntegrationTools/pfield/Mesh.hh, include/field_input/IntegrationTools/pfield/interpolation/Interpolator.hh, include/grains/OrderParameterRemapper.h, include/utilities/utilities.h, src/core/checkpoint.cc, src/core/initial_conditions/initialConditions.cc, src/core/inputFileReader.cc, src/core/outputResults.cc, src/core/solvers/solveIncrement.cc, src/core/userInputParameters.cc, src/core/variableAttributeLoader.cc, src/core/variableContainer.cc, src/grains/FloodFiller.cc, src/grains/OrderParameterRemapper.cc, src/grains/reassignGrains.cc
Added a custom exception to provide to deal.II's `Assert` and `AssertThrow`. In this case it's for features that haven't been implemented yet. It takes some context string to provide the user information as to what feature is not implemented.
This can be extended for other common exceptions that we may have.
In the future include `<core/exceptions.h>` rather than `<deal.II/base/exceptions.h>`
Closes #384 
=> Custom exceptions

CMakeLists.txt, cmake/setup_application.cmake
Most recent commit removed compatibility with deal.ii 9.5, I modified cmake files to fix this.
=> Fixing compatibility with deal.ii 9.5

include/core/variableAttributeLoader.h, src/core/variableAttributeLoader.cc
also removed const qualifier from insert functions. (Pointer contents are being modified)
=> Added template instantiations for vector, set, list of inserted dependencies

src/core/checkpoint.cc
Removing `std::filesystem` because some compilers like intel don't support it even though they support C++17.
=> Remove std::filesystem

.github/workflows/linux.yml
Closes #326 and #305
Renaming CI to `linux-base` as there are no optional features of PRISMS-PF turned on. In the future we can have `linux-cuda`, `linux-sundials`, etc...
=> Update linux CI to run with ninja

src/core/initial_conditions/initialConditions.cc
Body contents were not cleared when reading a new file, leading to incorrect behavior when re-using a body object.
(Several other problems are present in IntegrationTools, but they don't seem to be causing immediate issues and may be addressed in v3.0.)
=> Minimal fix to input file reading

src/solvers/nonexplicit_linear_solver.cc, src/solvers/nonexplicit_self_nonlinear_solver.cc
Previously implicit solves would be solved in the 0th step leading to iterations + 1.
=> Skipping implicit solves in 0th step

src/core/outputResults.cc
Simple fix: the output file type, userInputs.output_file_type, was being printed as a string literal when it should have been a reference to a variable. This change correctly results in .pvtu output files with, e.g., Piece <Piece Source="solution-000.0.vtu"/> instead of <Piece Source="solution-000.0.userInputs.output_file_type"/>
=> Remove quotes from reference to userInputs.output_file_type

applications/eshelbyInclusion/ICs_and_BCs.cc, applications/eshelbyInclusion/customPDE.h, applications/eshelbyInclusion/equations.cc, applications/eshelbyInclusion/parameters.prm
Old Eshelby Application Update. Note, history is slightly messed up.
=> Old Prisms Eshelby App Updates
